### ISSUE TITLE
Extra key/value pair added to scoreboard.json on CREATE

### ISSUE THREAD

**Issue by peonicles** [jsstrn/ga-wdi-crud-exercise#1]
There seems to be an extra button key/value pair added to the object that's pushed onto the array. I'm getting stuff like :

```
{
    "player": "FUUUBARRR",
    "score": "13371337",
    "button": ""
}
```

Maybe you could add the values of player and score instead of pushing the entire object ? Something like :

```
 // create
 app.post('/scores', (req, res) => {
  const entry = req.body
  const newEntry = { 'player': entry.player, 'score': entry.score }
  scoreboard.push(newEntry)
  res.json(newEntry)
  fs.writeFileSync(absolute_path, JSON.stringify(scoreboard, null, 2))
})

```

**Comment by jsstrn** [comment]
:trophy: Thanks for pointing this out, @peonicles. Fixed it by removing the `name` attribute in the `<button>` tag.
